# Generated by Django 5.2.7 on 2025-10-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangarinorg', '0002_rename_title_task_title_alter_substask_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Substask',
            new_name='Subtask',
        ),
    ]
