# Generated by Django 5.2.7 on 2025-10-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangarinorg', '0003_rename_substask_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
